((magit-branch nil)
 (magit-cherry-pick
  ("--ff"))
 (magit-commit nil)
 (magit-dispatch nil)
 (magit-file-dispatch nil)
 (magit-push nil)
 (magit-remote\.<remote>\.*url "git@github.com:repelliuss/ptgen.git" "https://github.com/repelliuss/ptgen")
 (magit-status-jump nil)
 (screenshot-transient nil))
